[package]
name = "nyanpassu"
version = "0.1.0"
authors = ["panpanick <panpanick@openmailbox.org>"]

[dependencies]
nickel = "*"
hyper = "*"
rand = "0.3"

[dependencies.url]
git = "https://github.com/servo/rust-url"
